version: '3.9'

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - server_uploads:/app/uploads
  db:
    image: postgres
    container_name: postgres
    ports:
      - '6543:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ovc
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  server_uploads: