version: '3.9'

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE_NAME=ovc
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=9999h
      - ADMIN_LOGIN=123
      - ADMIN_PASSWORD=123
      - UPLOAD_PATH=/app/uploads
    volumes:
      - server_uploads:/app/uploads

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NUXT_PUBLIC_OVC_API_HOST=http://localhost:5000
      - NUXT_PUBLIC_API_URL=http://localhost:5000/api/v3

  admin:
    build: ./admin
    container_name: admin
    ports:
      - "3001:80"

  db:
    image: postgres
    container_name: postgres
    ports:
      - '6543:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ovc
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  server_uploads: