version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - '6543:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ovc
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: