version: '3.9'

services:
  server:
    image: siailyadev/overcreated-server:v3
    container_name: server
    ports:
      - "5000:5000"
    restart: always
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE_NAME
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - ADMIN_LOGIN
      - ADMIN_PASSWORD
      - UPLOAD_PATH
    volumes:
      - server_uploads:/app/uploads

  client:
    image: siailyadev/overcreated-client:v3
    container_name: client
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NUXT_PUBLIC_OVC_API_HOST
      - NUXT_PUBLIC_API_URL

  admin:
    image: siailyadev/overcreated-admin:v3
    container_name: admin
    ports:
      - "3001:80"

  db:
    image: postgres
    container_name: postgres
    ports:
      - '6543:5432'
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - backup:/var/lib/postgresql/backup

volumes:
  postgres_data:
  server_uploads:
  backup: