<template>
<div>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
  portfolio <br>
</div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: "accent-color-client",
  variant: "green"
})
</script>

<style scoped>

</style>
