name: overcreated CI via Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: siailyadev/overcreated:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker login -u ${{secrets.DOCKER_HUB_LOGIN}} -p ${{ secrets.DOCKER_HUB_PASSWD }}
          docker pull ${{secrets.DOCKER_HUB_LOGIN}}/overcreated:latest
          docker stop overcreated
          docker system prune -f
          docker run --name overcreated -dit -p 5088:5088 --restart=always siailyadev/overcreated:latest
